# Supabase Configuration
SUPABASE_URL = "https://kmjrnfskswctcyftjwxn.supabase.co"
SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImttanJuZnNrc3djdGN5ZnRqd3huIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkzOTg3MTMsImV4cCI6MjA3NDk3NDcxM30.0YcG77TVo2UA4H8LgqKHZXJDIcyN4utNtQQLR0ZNQn8"